name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install modules
      run: npm ci

    - name: Build typescript files
      run: npm run build

    - name: Run tests
      run: npm run test
